In [183]:
import sys
sys.path.append('../utils/')
sys.path.append('../models/')
from utils import *
from sap_batch import *

In [184]:
smr = SAP_Master_Reset()
smr.atp_batch()

[EVENT] STARTING TO SAVE TODAY HISTORY ATP RESULT
[EVENT] ATP_HISTORY HAS ALREADY SAVED TODAY. RPA IS INITIALIZING NOW
[EVENT] INSERT INFO:
 	 TABLE NAME:  ATP_HISTORY
 	 TABLE COLUMNS ARE BELOW Index(['Data_Type', '기준일자', '날짜', 'YYYYMM', 'CW', '제품명', 'Item_Code',
       'Power_Class', 'WH_Code', 'Tariff', 'WestEast', 'Intake_Shipments_FCST',
       'Intake_Shipments_ACTUAL', 'Soft_Allocation', 'Hard_Allocation',
       'CPO_shipped'],
      dtype='object')
[EVENT] SAVED ATTACHMENTS LOG WROTTEN IN RPA_DOWNLOAD_LOGS TABLE
[EVENT] STARTING TO SAVE TODAY HISTORY ATP_OUTBOUND RESULT
[EVENT] OUT_BOUND_HISTORY HAS ALREADY SAVED TODAY. RPA IS INITIALIZING NOW
[EVENT] INSERT INFO:
 	 TABLE NAME:  OUT_BOUND_HISTORY
 	 TABLE COLUMNS ARE BELOW Index(['Data_Type', 'Updated_Date', 'CustomerPO_Num', 'Customer_Name',
       'STATUS', 'DO_Num', 'Item_Code', 'Customer_Address', 'Product_Name',
       'Power_Class', 'Tariff', 'WH_Code', 'WH_Name', 'WestEast', 'Segment',
       'PCS', 'Pallet', 'MW', 'ASP', 'Revenue', 'CPO_PCS', 'CPO_Pallet',
       'CPO_MW', 'PO_Date', 'Requested_Delivery_Date', 'Updated_RDD',
       'Cargo_Release_Date', 'ETD', 'ETD_Lag', 'ATD', 'ETA', 'ATA',
       'TruckingCompany_Name', 'Incoterm', 'Unloading_Date',
       'Proof_Of_Delivery_Date', 'CPO_Status', 'Logi_Status'],
      dtype='object')
[EVENT] SAVED ATTACHMENTS LOG WROTTEN IN RPA_DOWNLOAD_LOGS TABLE
[EVENT] STARTING TO SAVE TODAY HISTORY ATP_ONHAND RESULT
[EVENT] ATP_ONHAND BATCH VIEW, ProductName COLUMN NULL CHECKING RESULT IS : 55
[EVENT] ATP_ONHAND BATCH VIEW, WH_Location COLUMN NULL CHECKING RESULT IS : 166
[WARNING] THIS ATTACHMENT HAS AN NULL VALUES.

TypeError: send_email() got an unexpected keyword argument 'warning'

In [248]:
view_names = [['ATP_OUTBOUND' , 'OUT_BOUND_HISTORY']
                    , ['ATP_ONHAND', 'ON_HAND_HISTORY']
                    , ['ATP_INBOUND_DOMESTIC', 'INBOUND_DOMESTIC_HISTORY']
                    , ['ATP_INBOUND_OVERSEA', 'INBOUND_OVERSEA_HISTORY']
                    , ['ATP_DELIVERY_STATUS_BI', 'DELIVERY_STATUS_HISTORY']]

# for name in view_names:
name = view_names[0]
smr.connect_azuredb()
smr.df = smr.fetch_data('select * from {}'.format(name[0]))

In [251]:
join_check_column_list = ['Product_Name', 'WH_Name']                
join_check_column_list_upper = list(map(str.upper,join_check_column_list))
nullcheck_cols = [col for col in smr.df.columns if col.upper() in join_check_column_list_upper]
nullcheck_total_result = []
if len(nullcheck_cols) > 0:
    for ncols in nullcheck_cols:
        nullcheck_result = smr.df[ncols].isnull().sum() + len(smr.df[smr.df[ncols] == ''])
        if nullcheck_result > 0:
            nullcheck_total_result.append([ncols, nullcheck_result])

if len(nullcheck_total_result) > 0:
    nullcheck_total_result = ['{} : {} ROWS MISSED'.format(i[0], i[1]) for i in nullcheck_total_result]
    nullcheck_total_result = ' <br> '.join(nullcheck_total_result)
    
    print(nullcheck_total_result)

Product_Name : 427 ROWS MISSED <br> WH_Name : 274 ROWS MISSED

In [252]:
smr.df.head()

,Data_Type,Updated_Date,CustomerPO_Num,Customer_Name,STATUS,DO_Num,Item_Code,Customer_Address,Product_Name,Power_Class,...,ETD_Lag,ATD,ETA,ATA,TruckingCompany_Name,Incoterm,Unloading_Date,Proof_Of_Delivery_Date,CPO_Status,Logi_Status
0,OSR,2022-06-15,PO-32755_PT2,BayWa r.e. Solar Systems LLC,CR,None,,None,None,NaN,...,None,None,None,None,None,DDP,None,None,AWAITING APPROVAL,None
1,OSR,2022-06-15,PO-32755_PT2,BayWa r.e. Solar Systems LLC,CR,None,,None,None,NaN,...,None,None,None,None,None,DDP,None,None,AWAITING APPROVAL,None
2,OSR,2022-06-15,PO-32755_PT2,BayWa r.e. Solar Systems LLC,CR,None,,None,None,NaN,...,None,None,None,None,None,DDP,None,None,AWAITING APPROVAL,None
3,OSR,2022-06-15,RH-qcells-001_PT1,"Revity EPC, LLC",CR,None,30391492,None,Q.PEAK DUO XL G11 BFG,580.0,...,None,None,None,None,None,DDP,None,None,AWAITING APPROVAL,None
4,OSR,2022-06-15,RH-qcells-001_PT1,"Revity EPC, LLC",CR,None,30391492,None,Q.PEAK DUO XL G11 BFG,580.0,...,None,None,None,None,None,DDP,None,None,AWAITING APPROVAL,None

In [253]:
nullcheck_cols

['Product_Name', 'WH_Name']